services:
  fast-api-server:
    build: .
    container_name: fast-api-server
    user: "${APP_UID}:${APP_GID}"
    ports:
      - "8989:8000"
    volumes:
      - ${HOST_INPUTS_DIR:-./images/inputs}:/app/images/inputs
      - ${HOST_OUTPUTS_DIR:-./images/outputs}:/app/images/outputs
    environment:
      - UESR=${APP_USER}
      - YOLO_MODEL_PATH=${YOLO_MODEL_PATH:-models/best.pt}
      - ORIGIN_IMAGE_DIR=${ORIGIN_IMAGE_DIR:-/app/images/inputs}
      - CROP_IMAGE_DIR=${CROP_IMAGE_DIR:-/app/images/outputs}
      - YOLO_CONFIDENCE=${YOLO_CONFIDENCE:-0.25}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-trash-rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE:-analysis.exchange}
      - RABBITMQ_REQUEST_QUEUE=${RABBITMQ_REQUEST_QUEUE:-analysis.request.queue}
      - RABBITMQ_RESULT_ROUTING_KEY=${RABBITMQ_RESULT_ROUTING_KEY:-analysis.result}
    networks:
      - trash-network
    restart: always

networks:
  trash-network:
    external: true
